name: Trigger a pkg.go.dev update

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update-pkg-go-dev:
    runs-on: ubuntu-24.04
    steps:
      - name: Update pkg.go.dev
        run: curl "https://proxy.golang.org/github.com/${GITHUB_REPOSITORY,,}/@v/${GITHUB_REF_NAME,,}.info"
