name: Trigger a pkg.go.dev update & upstream repo

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update-pkg-go-dev:
    runs-on: ubuntu-24.04
    steps:
      - name: Update pkg.go.dev
        if: github.event_name == 'release'
        run: |
          curl "https://proxy.golang.org/github.com/${GITHUB_REPOSITORY,,}/@v/${GITHUB_REF_NAME,,}.info"
          sleep 10
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.DEPENDABOT_TRIGGER_APP_ID }}
          private-key: ${{ secrets.DEPENDABOT_TRIGGER_APP_PRIVATE_KEY }}
          repositories: caddy-dns-opnsense
          permission-actions: write
      - name: Trigger upstream workflows
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'mietzen',
              repo: 'caddy-dns-opnsense',
              workflow_id: 'dependabot-trigger.yml',
              ref: 'master'
            })
